name: CodeCheck

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'

jobs:
  code-check:
    name: CodeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: prettier
        run: npm run format
      - name: eslint
        run: npm run lint
      - name: typecheck
        run: npm run typecheck

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Testing on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - name: testing
        run: npm run test
