name: Testing

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Testing on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - name: testing
        run: npm run test
