name: Testing

on:
  push:
    tags-ignore:
      - '*'
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Testing on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - name: testing
        run: npm run test
