name: Testing

on:
  push:
    tags-ignore:
      - '*'
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Testing on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - name: testing
        run: npm run test
